server:
  port: 8080
  ssl:
    enabled: false

spring:
  main:
    web-application-type: reactive
  application:
    name: curlylab_gateway

  redis:
    host: redis
    port: 6379

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_FIRST

      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**, /auth/**, /hairtypes/**
          filters:
            - RemoveRequestHeader=Content-Length
            - RemoveRequestHeader=Forwarded
            - RemoveRequestHeader=X-Forwarded-For
            - RemoveRequestHeader=X-Forwarded-Proto
            - RemoveRequestHeader=X-Forwarded-Port
            - RemoveRequestHeader=X-Forwarded-Host
            - name: Retry
              args:
                retries: 3
                statuses: SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
                methods: GET
            - name: CircuitBreaker
              args:
                name: userCB
                fallbackUri: forward:/fallback/user
                failureRateThreshold: 50
                minimumNumberOfCalls: 5
                slidingWindowSize: 10
                waitDurationInOpenState: 10s
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
            - name: CacheRequestBody

        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/products/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: SERVICE_UNAVAILABLE,BAD_GATEWAY
                methods: GET
            - name: CircuitBreaker
              args:
                name: productCB
                fallbackUri: forward:/fallback/product
                failureRateThreshold: 60
                minimumNumberOfCalls: 5
                slidingWindowSize: 10
                waitDurationInOpenState: 15s
                slowCallDurationThreshold: 2s
                slowCallRateThreshold: 50
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
                key-resolver: "#{@remoteAddrKeyResolver}"

        - id: blog-service
          uri: http://blog-service:8082
          predicates:
            - Path=/blog_records/**,/blog_subscribers/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses: SERVICE_UNAVAILABLE
            - name: CircuitBreaker
              args:
                name: blogCB
                fallbackUri: forward:/fallback/blog
                failureRateThreshold: 50
                slidingWindowType: TIME_BASED
                slidingWindowSize: 60
                waitDurationInOpenState: 30s
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@remoteAddrKeyResolver}"

        - id: composition-service
          uri: http://composition-service:8000
          predicates:
            - Path=/analyze/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: SERVICE_UNAVAILABLE
            - name: CircuitBreaker
              args:
                name: compositionCB
                fallbackUri: forward:/fallback/composition
                failureRateThreshold: 70
                minimumNumberOfCalls: 10
                waitDurationInOpenState: 20s
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@remoteAddrKeyResolver}"

        - id: hairtyping-service
          uri: http://hairtyping-service:8111
          predicates:
            - Path=/analyze/**
          filters:
            - name: Retry
              args:
                retries: 2
                statuses: GATEWAY_TIMEOUT
            - name: CircuitBreaker
              args:
                name: hairtypingCB
                fallbackUri: forward:/fallback/hairtyping
                slowCallDurationThreshold: 3s
                slowCallRateThreshold: 60
                maxWaitDurationInHalfOpenState: 10s
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@remoteAddrKeyResolver}"

      httpclient:
        connect-timeout: 10000
        response-timeout: 25s
        pool:
          max-idle-time: 60s
          max-life-time: 120s

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:[*]"
              - "https://*.curlylab.*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers:
              - Content-Disposition
              - X-RateLimit-Remaining
            max-age: 3600

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.web.reactive.DispatcherHandler: TRACE
    org.springframework.data.redis: DEBUG
    io.lettuce.core: WARN
    org.springframework.retry: TRACE